name: Cypress Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start the app and wait for the server to be available
      - name: Start the app
        run: |
          PORT=3001 npm start &  # Start your app on port 3001
          npx wait-on http://localhost:3001  # Wait for the server to be up

      # Install Cypress
      - name: Install Cypress
        run: npm install cypress

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
